"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Globe } from "lucide-react";
import { create } from "zustand";

interface LangContextType {
  lang: "es" | "en";
  toggle: () => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.bikes": "Bicicletas",
    "nav.gallery": "Galería",
    "nav.testimonials": "Testimonios",
    "nav.reserve": "Reservar",
    "nav.contact": "Contacto",
    "hero.badge": "Granada, Nicaragua",
    "hero.title.1": "Explorá Granada",
    "hero.title.2": "en bicicleta",
    "hero.subtitle": "Alquiler fácil, recorridos inolvidables.",
    "hero.subtitle2": "Reservá en minutos y descubrí la ciudad colonial sobre dos ruedas.",
    "hero.cta1": "Reservar Ahora",
    "hero.cta2": "Ver Bicicletas",
    "hero.scroll": "Descubrí más",
    "features.badge": "¿Por qué elegirnos?",
    "features.title.1": "¿Por qué",
    "features.title.2": "BiciVentura",
    "features.subtitle": "Más que un alquiler, una experiencia completa para descubrir Granada a tu ritmo.",
    "features.f1.title": "Tarifas en córdobas",
    "features.f1.desc": "Ofrecemos los mejores precios locales cotizados directamente en Córdobas, sin cargos ocultos ni sorpresas.",
    "features.f2.title": "Rutas recomendadas con mapas",
    "features.f2.desc": "Te proporcionamos mapas ilustrados de las mejores rutas por la ciudad colonial, el malecón del lago y las isletas.",
    "features.f3.title": "Pick-up y drop-off flexible",
    "features.f3.desc": "Recogé tu bici en nuestro punto central frente a la Catedral o te la llevamos a tu hotel. ¡Tú elegís!",
    "bikes.badge": "Nuestra flota",
    "bikes.title.1": "Elegí tu",
    "bikes.title.2": "compañera de ruta",
    "bikes.subtitle": "Bicicletas para cada estilo de aventura. Todas incluyen mapa gratuito de Granada.",
    "bikes.all": "Todas",
    "bikes.reserve": "Reservar esta bici",
    "bikes.unavailable": "No disponible",
    "bikes.perhour": "Por hora",
    "bikes.perday": "Por día",
    "bikes.accessories": "Complementos disponibles",
    "gallery.badge": "Galería",
    "gallery.title.1": "Granada sobre",
    "gallery.title.2": "ruedas",
    "gallery.subtitle": "Momentos capturados de aventureros explorando la perla colonial de Nicaragua.",
    "gallery.all": "Todas",
    "gallery.happy": "Clientes felices",
    "gallery.landscapes": "Paisajes",
    "gallery.details": "Detalles",
    "testimonials.badge": "Testimonios",
    "testimonials.title.1": "Lo que dicen nuestros",
    "testimonials.title.2": "aventureros",
    "testimonials.subtitle": "Experiencias reales de viajeros que descubrieron Granada con BiciVentura.",
    "testimonials.reviews": "Basado en",
    "testimonials.reviews2": "reseñas",
    "testimonials.leavereview": "¿Pedaleaste con nosotros? ¡Contanos tu experiencia!",
    "testimonials.cta": "Dejar una reseña",
    "cta.title.1": "¿Listo para",
    "cta.title.2": "rodar",
    "cta.subtitle": "No esperes más. Reservá tu bicicleta y empezá a explorar la perla colonial de Centroamérica.",
    "cta.cta1": "Reservá ahora",
    "cta.cta2": "Hablá con nosotros",
    "contact.badge": "Contacto",
    "contact.title.1": "Hablá con",
    "contact.title.2": "nosotros",
    "contact.subtitle": "¿Tenés preguntas? Estamos acá para ayudarte a planear tu aventura en bicicleta.",
    "contact.location": "Ubicación",
    "contact.hours": "Horarios",
    "contact.phone": "Teléfono / WhatsApp",
    "contact.email": "Email",
    "contact.whatsapp": "Chateá por WhatsApp",
    "contact.form.title": "Envianos un mensaje",
    "contact.form.sent": "¡Mensaje enviado!",
    "contact.form.sentmsg": "Te responderemos lo antes posible.",
    "contact.form.name": "Nombre",
    "contact.form.email": "Email",
    "contact.form.subject": "Asunto",
    "contact.form.message": "Mensaje",
    "contact.form.send": "Enviar mensaje",
    "contact.form.ph_name": "Tu nombre",
    "contact.form.ph_email": "tu@email.com",
    "contact.form.ph_subject": "¿En qué podemos ayudarte?",
    "contact.form.ph_message": "Escribí tu mensaje aquí...",
    "contact.faq": "Preguntas frecuentes",
    "footer.tagline": "Pedaleá la aventura colonial. Alquiler de bicicletas en el corazón de Granada, Nicaragua.",
    "footer.links": "Enlaces",
    "footer.services": "Servicios",
    "footer.contact": "Contacto",
    "footer.rights": "Hecho con amor en Granada, Nicaragua",
    "float.reserve": "Reservar ahora",
    "reserve.badge": "Reservar",
    "reserve.title.1": "Reservá tu",
    "reserve.title.2": "aventura",
    "reserve.subtitle": "Completá los 3 pasos y recibí tu confirmación por email.",
    "reserve.step1": "Elegí tus ruedas",
    "reserve.step2": "Fecha y hora",
    "reserve.step3": "Tus datos",
    "reserve.previous": "Anterior",
    "reserve.next": "Siguiente",
    "reserve.confirm": "Confirmar reserva",
    "reserve.cart": "Carrito",
    "reserve.accessories": "Complementos",
    "reserve.perday": "Precio por 1 día",
    "reserve.pickup": "Fecha de recogida",
    "reserve.return": "Fecha de devolución",
    "reserve.pickupTime": "Hora de recogida",
    "reserve.returnTime": "Hora de devolución",
    "reserve.duration": "Duración",
    "reserve.bikes": "Bicicletas",
    "reserve.total": "Total",
    "reserve.day": "día",
    "reserve.days": "días",
    "reserve.summary": "Resumen del pedido",
    "reserve.payment": "Pago en persona al momento de la recogida",
    "reserve.nombres": "Nombres *",
    "reserve.apellidos": "Apellidos *",
    "reserve.codigo": "Código *",
    "reserve.genero": "Género *",
    "reserve.nacionalidad": "Nacionalidad *",
    "reserve.telefono": "Teléfono *",
    "reserve.ph_nombres": "Tus nombres",
    "reserve.ph_apellidos": "Tus apellidos",
    "reserve.ph_codigo": "Tu código o identificación",
    "reserve.ph_telefono": "Tu número telefónico",
    "reserve.select_gender": "Seleccionar género",
    "reserve.confirmed": "¡Reserva recibida!",
    "reserve.thanks": "Hemos recibido tu solicitud de reserva.",
    "reserve.email_info": "Puedes guardar tu código de reserva para la recogida de la flota.",
    "reserve.meeting": "Punto de encuentro:",
    "reserve.meeting_addr": "Frente a la Catedral, Calle La Calzada",
    "reserve.another": "Hacer otra reserva",
    "reserve.select_time": "Seleccionar hora",
    // New translations added
    "accessories.helmet": "Casco de seguridad",
    "accessories.lock": "Candado U-Lock",
    "accessories.child_seat": "Silla para niños",
    "accessories.picnic_kit": "Kit de picnic",
    "accessories.water_bottle": "Botella de agua",
    "accessories.extra_light": "Farol extra",
    "reserve.select_nationality": "Seleccionar",
    "reserve.select_placeholder": "Seleccionar",
    "bikes.type.urbana": "Urbana",
    "bikes.type.montaña": "Montaña",
    "bikes.type.cruiser": "Cruiser",
    "bikes.type.tandem": "Tandem",
    "bikes.type_plural.urbana": "Urbanas",
    "bikes.type_plural.montaña": "Montaña",
    "bikes.type_plural.cruiser": "Cruiser",
    "bikes.type_plural.tandem": "Tandem",
    "bikes.type_plural.todos": "Todas",
    "bikes.granada-cruiser.desc": "Bicicleta estilo cruiser perfecta para pasear por las calles coloniales. Asiento cómodo, canasta incluida y diseño vintage que combina con la ciudad.",
    "bikes.granada-cruiser.f1": "Canasta",
    "bikes.granada-cruiser.f2": "Asiento acolchado",
    "bikes.granada-cruiser.f3": "Cambios 3 velocidades",
    "bikes.granada-cruiser.f4": "Faro LED",
    "bikes.mombacho-mtb.desc": "Mountain bike robusta para aventuras en los senderos del volcán Mombacho o rutas fuera del asfalto. Suspensión delantera y frenos de disco.",
    "bikes.mombacho-mtb.f1": "Suspensión delantera",
    "bikes.mombacho-mtb.f2": "Frenos de disco",
    "bikes.mombacho-mtb.f3": "21 velocidades",
    "bikes.mombacho-mtb.f4": "Llanta antipinchaduras",
    "bikes.colonial-urban.desc": "Bicicleta urbana clásica en tono colonial amarillo. Ideal para recorrer el centro histórico y tomar fotos. Liviana y fácil de manejar.",
    "bikes.colonial-urban.f1": "Canasta tejida",
    "bikes.colonial-urban.f2": "Portaequipajes",
    "bikes.colonial-urban.f3": "7 velocidades",
    "bikes.colonial-urban.f4": "Casco incluido",
    "bikes.tandem-amigos.desc": "Bicicleta tandem para compartir la aventura. Perfecta para parejas o amigos que quieren pedalear juntos por el malecón del lago.",
    "bikes.tandem-amigos.f1": "Doble asiento",
    "bikes.tandem-amigos.f2": "Frenos independientes",
    "bikes.tandem-amigos.f3": "7 velocidades",
    "bikes.tandem-amigos.f4": "Soporte para celular",
    "testimonials.t1.text": "¡Increíble experiencia! Las bicis estaban en perfecto estado y el mapa que nos dieron fue super útil. Granada es aún más hermosa cuando la recorrés pedaleando. Volvería sin dudar.",
    "testimonials.t1.date": "Diciembre 2024",
    "testimonials.t2.text": "¡La mejor manera de explorar Granada! El equipo fue super amable y las bicis son de alta calidad. Alquilamos la Mombacho MTB y tuvimos una aventura increíble en los senderos del volcán.",
    "testimonials.t2.date": "Noviembre 2024",
    "testimonials.t3.text": "Alquilamos el tandem para pasear por el malecón al atardecer. ¡Fue mágico! El servicio de entrega al hotel fue un gran plus. Muy recomendados para familias.",
    "testimonials.t3.date": "Enero 2025",
    "testimonials.t4.text": "Como ciclista experimentada, puedo decir que las bicis de BiciVentura están bien mantenidas. Los recorridos recomendados por las isletas fueron lo mejor de nuestro viaje a Nicaragua.",
    "testimonials.t4.date": "Octubre 2024",
    "testimonials.t5.text": "Reservamos online y todo fue súper fácil. La bici urban nos permitió conocer cada rincón de la ciudad colonial. Los precios son muy justos para la calidad del servicio.",
    "testimonials.t5.date": "Febrero 2025",
    "testimonials.t6.text": "¡Magnífico! Granada es aún más hermosa desde una bicicleta. La arquitectura colonial, el lago, el volcán... todo es perfecto. BiciVentura lo hizo fácil y divertido.",
    "testimonials.t6.date": "Enero 2025",
    "promotions.badge": "Ofertas Especiales",
    "promotions.title.1": "Nuestras",
    "promotions.title.2": "Promociones",
    "promotions.subtitle": "Aprovechá nuestras tarifas promocionales exclusivas para recorrer Granada al mejor precio.",
    "promotions.p1.title": "Fin de Semana Colonial",
    "promotions.p1.desc": "Alquilá por 2 días completos y te regalamos el 3er día. ¡Ideal para un viaje largo!",
    "promotions.p2.title": "Descuento de Grupo",
    "promotions.p2.desc": "Ahorrá un 15% en el costo total si alquilás 4 o más bicicletas al mismo tiempo.",
    "promotions.p3.title": "Aventura MTB & Picnic",
    "promotions.p3.desc": "Alquilá 2 Mombacho MTB por un día completo y te incluimos el Kit de Picnic gratis.",
    "about.badge": "Quiénes Somos",
    "about.title.1": "Misión, Visión",
    "about.title.2": "y Valores",
    "about.mission.title": "Nuestra Misión",
    "about.mission.desc": "Promover el turismo sostenible y saludable en Granada a través del ciclismo, brindando una experiencia accesible, segura y enriquecedora sobre ruedas.",
    "about.vision.title": "Nuestra Visión",
    "about.vision.desc": "Convertirnos en la plataforma líder y más confiable de alquiler de bicicletas en Centroamérica, reconocida por nuestra flota impecable, compromiso ecológico e integración cultural.",
    "about.values.title": "Nuestros Valores",
    "about.values.v1.title": "Hospitalidad",
    "about.values.v1.desc": "Tratamos a cada viajero como un amigo, compartiendo los mejores consejos locales.",
    "about.values.v2.title": "Sostenibilidad",
    "about.values.v2.desc": "Cuidamos el medio ambiente promoviendo la movilidad limpia en la ciudad.",
    "about.values.v3.title": "Calidad",
    "about.values.v3.desc": "Garantizamos bicicletas seguras, limpias y listas para pedalear.",
    "about.values.v4.title": "Aventura",
    "about.values.v4.desc": "Inspiramos el deseo de explorar y descubrir caminos inolvidables.",
    "footer.service1": "Alquiler por hora y día",
    "footer.service2": "Rutas recomendadas",
    "footer.service3": "Pick-up y drop-off flexible",
    "footer.service4": "Tours guiados",
    "footer.all_rights": "Todos los derechos reservados.",
  },
  en: {
    "nav.home": "Home",
    "nav.bikes": "Bicycles",
    "nav.gallery": "Gallery",
    "nav.testimonials": "Testimonials",
    "nav.reserve": "Book Now",
    "nav.contact": "Contact",
    "hero.badge": "Granada, Nicaragua",
    "hero.title.1": "Explore Granada",
    "hero.title.2": "by bike",
    "hero.subtitle": "Easy rental, unforgettable rides.",
    "hero.subtitle2": "Book in minutes and discover the colonial city on two wheels.",
    "hero.cta1": "Book Now",
    "hero.cta2": "View Bicycles",
    "hero.scroll": "Discover more",
    "features.badge": "Why choose us?",
    "features.title.1": "Why",
    "features.title.2": "BiciVentura",
    "features.subtitle": "More than a rental, a complete experience to discover Granada at your own pace.",
    "features.f1.title": "Rates in Cordobas",
    "features.f1.desc": "We offer the best local prices quoted directly in Cordobas, with no hidden charges or surprises.",
    "features.f2.title": "Recommended routes with maps",
    "features.f2.desc": "We provide illustrated maps of the best routes through the colonial city, lake waterfront, and islets.",
    "features.f3.title": "Flexible pick-up & drop-off",
    "features.f3.desc": "Pick up your bike at our central point in front of the Cathedral or we deliver it to your hotel. You choose!",
    "bikes.badge": "Our fleet",
    "bikes.title.1": "Choose your",
    "bikes.title.2": "riding companion",
    "bikes.subtitle": "Bikes for every adventure style. All include a free map of Granada.",
    "bikes.all": "All",
    "bikes.reserve": "Book this bike",
    "bikes.unavailable": "Unavailable",
    "bikes.perhour": "Per hour",
    "bikes.perday": "Per day",
    "bikes.accessories": "Available accessories",
    "gallery.badge": "Gallery",
    "gallery.title.1": "Granada on",
    "gallery.title.2": "wheels",
    "gallery.subtitle": "Captured moments of adventurers exploring the colonial pearl of Nicaragua.",
    "gallery.all": "All",
    "gallery.happy": "Happy clients",
    "gallery.landscapes": "Landscapes",
    "gallery.details": "Details",
    "testimonials.badge": "Testimonials",
    "testimonials.title.1": "What our",
    "testimonials.title.2": "adventurers say",
    "testimonials.subtitle": "Real experiences from travelers who discovered Granada with BiciVentura.",
    "testimonials.reviews": "Based on",
    "testimonials.reviews2": "reviews",
    "testimonials.leavereview": "Rode with us? Tell us about your experience!",
    "testimonials.cta": "Leave a review",
    "cta.title.1": "Ready to",
    "cta.title.2": "ride",
    "cta.subtitle": "Don't wait any longer. Book your bike and start exploring the colonial pearl of Central America.",
    "cta.cta1": "Book now",
    "cta.cta2": "Talk to us",
    "contact.badge": "Contact",
    "contact.title.1": "Talk to",
    "contact.title.2": "us",
    "contact.subtitle": "Have questions? We're here to help you plan your biking adventure.",
    "contact.location": "Location",
    "contact.hours": "Hours",
    "contact.phone": "Phone / WhatsApp",
    "contact.email": "Email",
    "contact.whatsapp": "Chat on WhatsApp",
    "contact.form.title": "Send us a message",
    "contact.form.sent": "Message sent!",
    "contact.form.sentmsg": "We'll get back to you as soon as possible.",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.send": "Send message",
    "contact.form.ph_name": "Your name",
    "contact.form.ph_email": "your@email.com",
    "contact.form.ph_subject": "How can we help you?",
    "contact.form.ph_message": "Write your message here...",
    "contact.faq": "Frequently asked questions",
    "footer.tagline": "Pedal the colonial adventure. Bike rental in the heart of Granada, Nicaragua.",
    "footer.links": "Links",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "Made with love in Granada, Nicaragua",
    "float.reserve": "Book now",
    "reserve.badge": "Book",
    "reserve.title.1": "Book your",
    "reserve.title.2": "adventure",
    "reserve.subtitle": "Complete the 3 steps and receive your email confirmation.",
    "reserve.step1": "Choose your wheels",
    "reserve.step2": "Date & time",
    "reserve.step3": "Your details",
    "reserve.previous": "Previous",
    "reserve.next": "Next",
    "reserve.confirm": "Confirm booking",
    "reserve.cart": "Cart",
    "reserve.accessories": "Accessories",
    "reserve.perday": "Price for 1 day",
    "reserve.pickup": "Pickup date",
    "reserve.return": "Return date",
    "reserve.pickupTime": "Pickup time",
    "reserve.returnTime": "Return time",
    "reserve.duration": "Duration",
    "reserve.bikes": "Bikes",
    "reserve.total": "Total",
    "reserve.day": "day",
    "reserve.days": "days",
    "reserve.summary": "Order summary",
    "reserve.payment": "Pay in person at pickup",
    "reserve.nombres": "First Names *",
    "reserve.apellidos": "Last Names *",
    "reserve.codigo": "Code *",
    "reserve.genero": "Gender *",
    "reserve.nacionalidad": "Nationality *",
    "reserve.telefono": "Phone *",
    "reserve.ph_nombres": "Your first names",
    "reserve.ph_apellidos": "Your last names",
    "reserve.ph_codigo": "Your code or ID",
    "reserve.ph_telefono": "Your phone number",
    "reserve.select_gender": "Select gender",
    "reserve.confirmed": "Booking received!",
    "reserve.thanks": "We've received your booking request.",
    "reserve.email_info": "You can save your booking code for fleet pickup.",
    "reserve.meeting": "Meeting point:",
    "reserve.meeting_addr": "In front of the Cathedral, Calle La Calzada",
    "reserve.another": "Make another booking",
    "reserve.select_time": "Select time",
    // New translations added
    "accessories.helmet": "Safety helmet",
    "accessories.lock": "U-Lock padlock",
    "accessories.child_seat": "Child seat",
    "accessories.picnic_kit": "Picnic kit",
    "accessories.water_bottle": "Water bottle",
    "accessories.extra_light": "Extra light",
    "reserve.select_nationality": "Select",
    "reserve.select_placeholder": "Select",
    "bikes.type.urbana": "Urban",
    "bikes.type.montaña": "Mountain",
    "bikes.type.cruiser": "Cruiser",
    "bikes.type.tandem": "Tandem",
    "bikes.type_plural.urbana": "Urban",
    "bikes.type_plural.montaña": "Mountain",
    "bikes.type_plural.cruiser": "Cruiser",
    "bikes.type_plural.tandem": "Tandem",
    "bikes.type_plural.todos": "All",
    "bikes.granada-cruiser.desc": "Cruiser style bicycle perfect for riding through colonial streets. Comfortable seat, basket included, and vintage design that matches the city.",
    "bikes.granada-cruiser.f1": "Basket",
    "bikes.granada-cruiser.f2": "Padded seat",
    "bikes.granada-cruiser.f3": "3-speed gears",
    "bikes.granada-cruiser.f4": "LED headlight",
    "bikes.mombacho-mtb.desc": "Robust mountain bike for adventures on the trails of the Mombacho volcano or off-road routes. Front suspension and disc brakes.",
    "bikes.mombacho-mtb.f1": "Front suspension",
    "bikes.mombacho-mtb.f2": "Disc brakes",
    "bikes.mombacho-mtb.f3": "21-speed",
    "bikes.mombacho-mtb.f4": "Puncture-resistant tires",
    "bikes.colonial-urban.desc": "Classic urban bike in colonial yellow tone. Ideal for touring the historic center and taking photos. Lightweight and easy to handle.",
    "bikes.colonial-urban.f1": "Woven basket",
    "bikes.colonial-urban.f2": "Luggage rack",
    "bikes.colonial-urban.f3": "7-speed",
    "bikes.colonial-urban.f4": "Helmet included",
    "bikes.tandem-amigos.desc": "Tandem bicycle to share the adventure. Perfect for couples or friends who want to pedal together along the lake waterfront.",
    "bikes.tandem-amigos.f1": "Double seat",
    "bikes.tandem-amigos.f2": "Independent brakes",
    "bikes.tandem-amigos.f3": "7-speed",
    "bikes.tandem-amigos.f4": "Phone mount",
    "testimonials.t1.text": "Amazing experience! The bikes were in perfect condition and the map they gave us was super helpful. Granada is even more beautiful when you explore it by pedaling. I would return without hesitation.",
    "testimonials.t1.date": "December 2024",
    "testimonials.t2.text": "The best way to explore Granada! The team was super friendly and the bikes are high quality. We rented the Mombacho MTB and had an amazing adventure on the volcano trails.",
    "testimonials.t2.date": "November 2024",
    "testimonials.t3.text": "We rented the tandem to ride along the waterfront at sunset. It was magical! The hotel delivery service was a big plus. Highly recommended for families.",
    "testimonials.t3.date": "January 2025",
    "testimonials.t4.text": "As an experienced cyclist, I can say BiciVentura's bikes are very well maintained. The recommended rides around the islets were the absolute highlight of our trip to Nicaragua.",
    "testimonials.t4.date": "October 2024",
    "testimonials.t5.text": "We booked online and everything was super easy. The urban bike allowed us to know every corner of the colonial city. The prices are very fair for the quality of the service.",
    "testimonials.t5.date": "February 2025",
    "testimonials.t6.text": "Magnifique! Granada is even more beautiful from a bicycle. The colonial architecture, the lake, the volcano... everything is perfect. BiciVentura made it easy and fun.",
    "testimonials.t6.date": "January 2025",
    "promotions.badge": "Special Offers",
    "promotions.title.1": "Our",
    "promotions.title.2": "Promotions",
    "promotions.subtitle": "Take advantage of our exclusive promotional rates to explore Granada at the best price.",
    "promotions.p1.title": "Colonial Weekend",
    "promotions.p1.desc": "Rent for 2 full days and get the 3rd day free. Ideal for a long trip!",
    "promotions.p2.title": "Group Discount",
    "promotions.p2.desc": "Save 15% on the total cost if you rent 4 or more bikes at the same time.",
    "promotions.p3.title": "MTB & Picnic Adventure",
    "promotions.p3.desc": "Rent 2 Mombacho MTBs for a full day and get a free Picnic Kit included.",
    "about.badge": "About Us",
    "about.title.1": "Mission, Vision",
    "about.title.2": "and Values",
    "about.mission.title": "Our Mission",
    "about.mission.desc": "To promote sustainable and healthy tourism in Granada through cycling, providing an accessible, safe, and enriching experience on wheels.",
    "about.vision.title": "Our Vision",
    "about.vision.desc": "To become the leading and most trusted bicycle rental platform in Central America, recognized for our pristine fleet, green commitment, and cultural integration.",
    "about.values.title": "Our Values",
    "about.values.v1.title": "Hospitality",
    "about.values.v1.desc": "We treat every traveler as a friend, sharing the best local tips.",
    "about.values.v2.title": "Sustainability",
    "about.values.v2.desc": "We care for the environment by promoting clean mobility in the city.",
    "about.values.v3.title": "Quality",
    "about.values.v3.desc": "We guarantee safe, clean, and ready-to-pedal bicycles.",
    "about.values.v4.title": "Adventure",
    "about.values.v4.desc": "We inspire the desire to explore and discover unforgettable trails.",
    "footer.service1": "Hourly & daily rentals",
    "footer.service2": "Recommended routes",
    "footer.service3": "Flexible pick-up & drop-off",
    "footer.service4": "Guided tours",
    "footer.all_rights": "All rights reserved.",
  },
};

interface LanguageState {
  lang: "es" | "en";
  setLang: (lang: "es" | "en") => void;
  toggle: () => void;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  lang: "es",
  setLang: (lang) => set({ lang }),
  toggle: () => set((state) => ({ lang: state.lang === "es" ? "en" : "es" })),
}));

export function useTranslation() {
  const { lang, toggle } = useLanguageStore();

  const t = (key: string): string => {
    return translations[lang][key] || translations["es"][key] || key;
  };

  return { lang, toggle, t };
}

export function LanguageToggle({
  lang,
  toggle,
}: {
  lang: "es" | "en";
  toggle: () => void;
}) {
  return (
    <button
      onClick={toggle}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-medium bg-white/10 hover:bg-white/20 text-white/80 hover:text-white transition-all duration-200"
      aria-label="Toggle language"
    >
      <Globe className="w-3.5 h-3.5" />
      <span>{lang === "es" ? "EN" : "ES"}</span>
    </button>
  );
}
