"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Globe } from "lucide-react";

interface LangContextType {
  lang: "es" | "en";
  toggle: () => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.bikes": "Bicicletas",
    "nav.gallery": "Galería",
    "nav.testimonials": "Testimonios",
    "nav.reserve": "Reservar",
    "nav.contact": "Contacto",
    "hero.badge": "Granada, Nicaragua",
    "hero.title.1": "Explorá Granada",
    "hero.title.2": "en bicicleta",
    "hero.subtitle": "Alquiler fácil, recorridos inolvidables.",
    "hero.subtitle2": "Reservá en minutos y descubrí la ciudad colonial sobre dos ruedas.",
    "hero.cta1": "Reservar Ahora",
    "hero.cta2": "Ver Bicicletas",
    "hero.scroll": "Descubrí más",
    "features.badge": "¿Por qué elegirnos?",
    "features.title.1": "¿Por qué",
    "features.title.2": "BiciVentura",
    "features.subtitle": "Más que un alquiler, una experiencia completa para descubrir Granada a tu ritmo.",
    "features.f1.title": "Bicicletas en excelente estado",
    "features.f1.desc": "Nuestra flota se mantiene impecable. Cada bici recibe mantenimiento preventivo semanal para tu seguridad y comodidad.",
    "features.f2.title": "Rutas recomendadas con mapas",
    "features.f2.desc": "Te proporcionamos mapas ilustrados de las mejores rutas por la ciudad colonial, el malecón del lago y las isletas.",
    "features.f3.title": "Pick-up y drop-off flexible",
    "features.f3.desc": "Recogé tu bici en nuestro punto central frente a la Catedral o te la llevamos a tu hotel. ¡Tú elegís!",
    "bikes.badge": "Nuestra flota",
    "bikes.title.1": "Elegí tu",
    "bikes.title.2": "compañera de ruta",
    "bikes.subtitle": "Bicicletas para cada estilo de aventura. Todas incluyen mapa gratuito de Granada.",
    "bikes.all": "Todas",
    "bikes.reserve": "Reservar esta bici",
    "bikes.unavailable": "No disponible",
    "bikes.perhour": "Por hora",
    "bikes.perday": "Por día",
    "bikes.accessories": "Complementos disponibles",
    "gallery.badge": "Galería",
    "gallery.title.1": "Granada sobre",
    "gallery.title.2": "ruedas",
    "gallery.subtitle": "Momentos capturados de aventureros explorando la perla colonial de Nicaragua.",
    "gallery.all": "Todas",
    "gallery.happy": "Clientes felices",
    "gallery.landscapes": "Paisajes",
    "gallery.details": "Detalles",
    "testimonials.badge": "Testimonios",
    "testimonials.title.1": "Lo que dicen nuestros",
    "testimonials.title.2": "aventureros",
    "testimonials.subtitle": "Experiencias reales de viajeros que descubrieron Granada con BiciVentura.",
    "testimonials.reviews": "Basado en",
    "testimonials.reviews2": "reseñas",
    "testimonials.leavereview": "¿Pedaleaste con nosotros? ¡Contanos tu experiencia!",
    "testimonials.cta": "Dejar una reseña",
    "cta.title.1": "¿Listo para",
    "cta.title.2": "rodar",
    "cta.subtitle": "No esperes más. Reservá tu bicicleta y empezá a explorar la perla colonial de Centroamérica.",
    "cta.cta1": "Reservá ahora",
    "cta.cta2": "Hablá con nosotros",
    "contact.badge": "Contacto",
    "contact.title.1": "Hablá con",
    "contact.title.2": "nosotros",
    "contact.subtitle": "¿Tenés preguntas? Estamos acá para ayudarte a planear tu aventura en bicicleta.",
    "contact.location": "Ubicación",
    "contact.hours": "Horarios",
    "contact.phone": "Teléfono / WhatsApp",
    "contact.email": "Email",
    "contact.whatsapp": "Chateá por WhatsApp",
    "contact.form.title": "Envianos un mensaje",
    "contact.form.sent": "¡Mensaje enviado!",
    "contact.form.sentmsg": "Te responderemos lo antes posible.",
    "contact.form.name": "Nombre",
    "contact.form.email": "Email",
    "contact.form.subject": "Asunto",
    "contact.form.message": "Mensaje",
    "contact.form.send": "Enviar mensaje",
    "contact.form.ph_name": "Tu nombre",
    "contact.form.ph_email": "tu@email.com",
    "contact.form.ph_subject": "¿En qué podemos ayudarte?",
    "contact.form.ph_message": "Escribí tu mensaje aquí...",
    "contact.faq": "Preguntas frecuentes",
    "footer.tagline": "Pedaleá la aventura colonial. Alquiler de bicicletas en el corazón de Granada, Nicaragua.",
    "footer.links": "Enlaces",
    "footer.services": "Servicios",
    "footer.contact": "Contacto",
    "footer.rights": "Hecho con ❤️ en Granada, Nicaragua",
    "float.reserve": "Reservar ahora",
    "reserve.badge": "Reservar",
    "reserve.title.1": "Reservá tu",
    "reserve.title.2": "aventura",
    "reserve.subtitle": "Completá los 3 pasos y recibí tu confirmación por email.",
    "reserve.step1": "Elegí tus ruedas",
    "reserve.step2": "Fecha y hora",
    "reserve.step3": "Tus datos",
    "reserve.previous": "Anterior",
    "reserve.next": "Siguiente",
    "reserve.confirm": "Confirmar reserva",
    "reserve.cart": "Carrito",
    "reserve.accessories": "Complementos",
    "reserve.perday": "Precio por 1 día",
    "reserve.pickup": "Fecha de recogida",
    "reserve.return": "Fecha de devolución",
    "reserve.pickupTime": "Hora de recogida",
    "reserve.returnTime": "Hora de devolución",
    "reserve.duration": "Duración",
    "reserve.bikes": "Bicicletas",
    "reserve.total": "Total",
    "reserve.day": "día",
    "reserve.days": "días",
    "reserve.summary": "Resumen del pedido",
    "reserve.payment": "Pago en persona al momento de la recogida",
    "reserve.name": "Nombre completo *",
    "reserve.email": "Email *",
    "reserve.phone": "Teléfono / WhatsApp *",
    "reserve.nationality": "Nacionalidad",
    "reserve.notes": "Notas especiales",
    "reserve.ph_name": "Tu nombre",
    "reserve.ph_email": "tu@email.com",
    "reserve.ph_phone": "+505 1234 5678",
    "reserve.ph_notes": "¿Algo que debamos saber? (alergias, necesidades especiales, preferencias de ruta...)",
    "reserve.confirmed": "¡Reserva recibida! 🎉",
    "reserve.thanks": "Hemos recibido tu solicitud de reserva.",
    "reserve.email_info": "Te enviaremos un email de confirmación con todos los detalles y un código QR para tu recogida.",
    "reserve.meeting": "Punto de encuentro:",
    "reserve.meeting_addr": "Frente a la Catedral, Calle La Calzada",
    "reserve.another": "Hacer otra reserva",
    "reserve.select_time": "Seleccionar hora",
  },
  en: {
    "nav.home": "Home",
    "nav.bikes": "Bicycles",
    "nav.gallery": "Gallery",
    "nav.testimonials": "Testimonials",
    "nav.reserve": "Book Now",
    "nav.contact": "Contact",
    "hero.badge": "Granada, Nicaragua",
    "hero.title.1": "Explore Granada",
    "hero.title.2": "by bike",
    "hero.subtitle": "Easy rental, unforgettable rides.",
    "hero.subtitle2": "Book in minutes and discover the colonial city on two wheels.",
    "hero.cta1": "Book Now",
    "hero.cta2": "View Bicycles",
    "hero.scroll": "Discover more",
    "features.badge": "Why choose us?",
    "features.title.1": "Why",
    "features.title.2": "BiciVentura",
    "features.subtitle": "More than a rental, a complete experience to discover Granada at your own pace.",
    "features.f1.title": "Bikes in excellent condition",
    "features.f1.desc": "Our fleet is kept in pristine condition. Each bike receives weekly preventive maintenance for your safety and comfort.",
    "features.f2.title": "Recommended routes with maps",
    "features.f2.desc": "We provide illustrated maps of the best routes through the colonial city, lake waterfront, and islets.",
    "features.f3.title": "Flexible pick-up & drop-off",
    "features.f3.desc": "Pick up your bike at our central point in front of the Cathedral or we deliver it to your hotel. You choose!",
    "bikes.badge": "Our fleet",
    "bikes.title.1": "Choose your",
    "bikes.title.2": "riding companion",
    "bikes.subtitle": "Bikes for every adventure style. All include a free map of Granada.",
    "bikes.all": "All",
    "bikes.reserve": "Book this bike",
    "bikes.unavailable": "Unavailable",
    "bikes.perhour": "Per hour",
    "bikes.perday": "Per day",
    "bikes.accessories": "Available accessories",
    "gallery.badge": "Gallery",
    "gallery.title.1": "Granada on",
    "gallery.title.2": "wheels",
    "gallery.subtitle": "Captured moments of adventurers exploring the colonial pearl of Nicaragua.",
    "gallery.all": "All",
    "gallery.happy": "Happy clients",
    "gallery.landscapes": "Landscapes",
    "gallery.details": "Details",
    "testimonials.badge": "Testimonials",
    "testimonials.title.1": "What our",
    "testimonials.title.2": "adventurers say",
    "testimonials.subtitle": "Real experiences from travelers who discovered Granada with BiciVentura.",
    "testimonials.reviews": "Based on",
    "testimonials.reviews2": "reviews",
    "testimonials.leavereview": "Rode with us? Tell us about your experience!",
    "testimonials.cta": "Leave a review",
    "cta.title.1": "Ready to",
    "cta.title.2": "ride",
    "cta.subtitle": "Don't wait any longer. Book your bike and start exploring the colonial pearl of Central America.",
    "cta.cta1": "Book now",
    "cta.cta2": "Talk to us",
    "contact.badge": "Contact",
    "contact.title.1": "Talk to",
    "contact.title.2": "us",
    "contact.subtitle": "Have questions? We're here to help you plan your biking adventure.",
    "contact.location": "Location",
    "contact.hours": "Hours",
    "contact.phone": "Phone / WhatsApp",
    "contact.email": "Email",
    "contact.whatsapp": "Chat on WhatsApp",
    "contact.form.title": "Send us a message",
    "contact.form.sent": "Message sent!",
    "contact.form.sentmsg": "We'll get back to you as soon as possible.",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.send": "Send message",
    "contact.form.ph_name": "Your name",
    "contact.form.ph_email": "your@email.com",
    "contact.form.ph_subject": "How can we help you?",
    "contact.form.ph_message": "Write your message here...",
    "contact.faq": "Frequently asked questions",
    "footer.tagline": "Pedal the colonial adventure. Bike rental in the heart of Granada, Nicaragua.",
    "footer.links": "Links",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "Made with ❤️ in Granada, Nicaragua",
    "float.reserve": "Book now",
    "reserve.badge": "Book",
    "reserve.title.1": "Book your",
    "reserve.title.2": "adventure",
    "reserve.subtitle": "Complete the 3 steps and receive your email confirmation.",
    "reserve.step1": "Choose your wheels",
    "reserve.step2": "Date & time",
    "reserve.step3": "Your details",
    "reserve.previous": "Previous",
    "reserve.next": "Next",
    "reserve.confirm": "Confirm booking",
    "reserve.cart": "Cart",
    "reserve.accessories": "Accessories",
    "reserve.perday": "Price for 1 day",
    "reserve.pickup": "Pickup date",
    "reserve.return": "Return date",
    "reserve.pickupTime": "Pickup time",
    "reserve.returnTime": "Return time",
    "reserve.duration": "Duration",
    "reserve.bikes": "Bikes",
    "reserve.total": "Total",
    "reserve.day": "day",
    "reserve.days": "days",
    "reserve.summary": "Order summary",
    "reserve.payment": "Pay in person at pickup",
    "reserve.name": "Full name *",
    "reserve.email": "Email *",
    "reserve.phone": "Phone / WhatsApp *",
    "reserve.nationality": "Nationality",
    "reserve.notes": "Special notes",
    "reserve.ph_name": "Your name",
    "reserve.ph_email": "your@email.com",
    "reserve.ph_phone": "+505 1234 5678",
    "reserve.ph_notes": "Anything we should know? (allergies, special needs, route preferences...)",
    "reserve.confirmed": "Booking received! 🎉",
    "reserve.thanks": "We've received your booking request.",
    "reserve.email_info": "We'll send you a confirmation email with all details and a QR code for pickup.",
    "reserve.meeting": "Meeting point:",
    "reserve.meeting_addr": "In front of the Cathedral, Calle La Calzada",
    "reserve.another": "Make another booking",
    "reserve.select_time": "Select time",
  },
};

export function useTranslation() {
  const [lang, setLang] = useState<"es" | "en">("es");

  const toggle = () => setLang((prev) => (prev === "es" ? "en" : "es"));

  const t = (key: string): string => {
    return translations[lang][key] || translations["es"][key] || key;
  };

  return { lang, toggle, t };
}

export function LanguageToggle({
  lang,
  toggle,
}: {
  lang: "es" | "en";
  toggle: () => void;
}) {
  return (
    <button
      onClick={toggle}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-medium bg-white/10 hover:bg-white/20 text-white/80 hover:text-white transition-all duration-200"
      aria-label="Toggle language"
    >
      <Globe className="w-3.5 h-3.5" />
      <span>{lang === "es" ? "EN" : "ES"}</span>
    </button>
  );
}
